name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build client-debug
        run: |
          cmake --preset client-debug
          cmake --build --preset client-debug
      - name: Build client-release
        run: |
          cmake --preset client-release
          cmake --build --preset client-release
      - name: Build tool-debug
        run: |
          cmake --preset tool-debug
          cmake --build --preset tool-debug
      - name: Build tool-release
        run: |
          cmake --preset tool-release
          cmake --build --preset tool-release
